name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: drupal

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag itotko:$(date +%s)
