name: Itotko-master

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
 
    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        buildx-version: latest
        qemu-version: latest
      
    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}
      
    - name: Run Buildx
      run: |
        docker buildx build \
          --platform linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64 \
          --output "type=image,push=false" \
          --file ./docker/Dockerfile .
      
    - name: build-push
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: docker/Dockerfile
        repository: larskhansen/itotko
        tags: ${{ BUILD_NUMBER }}
