name: Itotko-master

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: install sass
      run: sudo apt install -y sass

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer update --no-dev --with-dependencies

    - name: Fetch Bootstrap sass
      working-directory: web/themes/custom/itotko_theme
      run: |
        git submodule init && git submodule update bootstrap

    - name: Build sass
      working-directory: web/themes/custom/itotko_theme
      run: |
        mkdir css && sass scss/style.scss css/style.css

    - name: build-push
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: docker/Dockerfile
        repository: larskhansen/itotko
        tags: latest
